server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://150.230.254.127:3306/scheme
    username: okane
    password: opi7opi7opi7@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false

github:
  webhook:
    secret: goranisamjichang